# Generated by Django 4.2.23 on 2025-08-05 15:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(verbose_name='title')),
                ('country', models.TextField(verbose_name='country')),
                ('body', models.TextField(verbose_name='content')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='app1/picture/', verbose_name='picture')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created_date_time')),
                ('edited', models.DateTimeField(auto_now_add=True, verbose_name='edited_date_time')),
                ('likes', models.IntegerField(default=0, verbose_name='likes_count')),
                ('dislikes', models.IntegerField(default=0, verbose_name='dislikes_count')),
                ('comments', models.IntegerField(default=0, verbose_name='comments_count')),
            ],
        ),
        migrations.CreateModel(
            name='Article_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='tag')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.article', verbose_name='ArticleID')),
            ],
        ),
    ]
