# Generated by Django 4.2.23 on 2025-08-07 06:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_article_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(verbose_name='comment')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created_date_time')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.article', verbose_name='ArticleID')),
            ],
        ),
    ]
