# Generated by Django 4.2.23 on 2025-08-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article_tag',
        ),
    ]
