# Generated by Django 4.2.23 on 2025-08-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_tags_username_article_user_name_remove_article_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='username',
            name='password',
            field=models.TextField(null=True, verbose_name='パスワード'),
        ),
        migrations.AlterField(
            model_name='username',
            name='score',
            field=models.IntegerField(default=0, verbose_name='スコア'),
        ),
        migrations.AlterField(
            model_name='username',
            name='user_name',
            field=models.TextField(verbose_name='ユーザ名'),
        ),
    ]
