# Generated by Django 4.2.23 on 2025-08-10 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_username_password_alter_username_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.TextField(default='ゲスト', verbose_name='user_name'),
        ),
        migrations.AlterField(
            model_name='username',
            name='password',
            field=models.TextField(blank=True, null=True, verbose_name='パスワード'),
        ),
    ]
