# Generated by Django 4.2.23 on 2025-08-11 05:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_username_password_alter_username_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField(verbose_name='タイトル')),
                ('body', models.TextField(verbose_name='本文')),
                ('tag', models.TextField(default='タグ指定なし', verbose_name='タグ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='作成時間')),
                ('articles', models.IntegerField(default=0, verbose_name='参照した投稿の数')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='score',
            field=models.IntegerField(default=0, verbose_name='score'),
        ),
    ]
