# Generated by Django 5.2.4 on 2025-08-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_merge_20250811_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='app1.tags', verbose_name='tag'),
        ),
    ]
