# Generated by Django 4.2.23 on 2025-08-11 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_tags_name'),
        ('app1', '0013_alter_tags_name'),
    ]

    operations = [
    ]
