# Generated by Django 5.2.4 on 2025-08-12 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_merge_0002_alter_tags_name_0013_alter_tags_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
