# Generated by Django 4.2.23 on 2025-08-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_merge_0002_alter_tags_name_0013_alter_tags_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidebook',
            name='tag_id',
        ),
        migrations.AddField(
            model_name='guidebook',
            name='tag',
            field=models.TextField(default='タグ指定なし', verbose_name='タグ'),
        ),
    ]
