# Generated by Django 4.2.23 on 2025-08-12 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_remove_guidebook_tag_id_guidebook_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
