# Generated by Django 5.2.4 on 2025-08-12 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_tags_name'),
        ('app1', '0016_alter_tags_name'),
    ]

    operations = [
    ]
