# Generated by Django 5.2.4 on 2025-08-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_merge_0015_alter_tags_name_0016_alter_tags_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=41, unique=True),
        ),
    ]
