# Generated by Django 4.2.23 on 2025-08-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_alter_tags_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidebook',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='app1/picture/', verbose_name='picture'),
        ),
    ]
