# Generated by Django 5.2.4 on 2025-08-12 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_guidebook_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidebook',
            name='picture',
        ),
    ]
