# Generated by Django 5.2.4 on 2025-08-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_remove_guidebook_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidebook',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='app1/picture/', verbose_name='picture'),
        ),
        migrations.AddField(
            model_name='guidebook',
            name='summary',
            field=models.TextField(null=True, verbose_name='要約'),
        ),
    ]
