# Generated by Django 5.2.4 on 2025-08-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_guidebook_picture_guidebook_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=42, unique=True),
        ),
    ]
