# Generated by Django 4.2.23 on 2025-08-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_alter_tags_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=43, unique=True),
        ),
    ]
