# Generated by Django 4.2.23 on 2025-08-12 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_alter_tags_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidebook',
            name='tag',
        ),
        migrations.AddField(
            model_name='guidebook',
            name='tag',
            field=models.ManyToManyField(blank=True, to='app1.tags', verbose_name='tag'),
        ),
    ]
