# Generated by Django 4.2.23 on 2025-08-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_remove_guidebook_tag_guidebook_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='dislikes_count'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='likes_count'),
        ),
    ]
