# Generated by Django 4.2.23 on 2025-08-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_comment_dislikes_comment_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='app1.tags', verbose_name='tag'),
        ),
    ]
