# Generated by Django 4.2.23 on 2025-08-22 01:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_alter_article_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.TextField(default='ゲスト', verbose_name='user_name')),
                ('likes', models.IntegerField(default=0, verbose_name='likes_count')),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.article', verbose_name='ArticleID')),
            ],
        ),
    ]
