# Generated by Django 4.2.23 on 2025-08-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_articlelike'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlelike',
            name='dislikes',
            field=models.IntegerField(default=0, verbose_name='dislikes_count'),
        ),
    ]
