# Generated by Django 4.2.23 on 2025-08-22 01:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_articlelike_dislikes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.TextField(default='ゲスト', verbose_name='user_name')),
                ('likes', models.IntegerField(default=0, verbose_name='likes_count')),
                ('dislikes', models.IntegerField(default=0, verbose_name='dislikes_count')),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.comment', verbose_name='CommentID')),
            ],
        ),
    ]
