# Generated by Django 4.2.23 on 2025-08-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.TextField(default='なし', verbose_name='tag'),
        ),
    ]
