# Generated by Django 4.2.23 on 2025-08-09 10:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_delete_article_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name', models.TextField(verbose_name='UserID')),
                ('score', models.IntegerField(default=0, verbose_name='score')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='user_name',
            field=models.TextField(default='ゲスト', verbose_name='user_name'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='app1.tags', verbose_name='tag'),
        ),
    ]
