# Generated by Django 4.2.23 on 2025-08-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_comment_user_name_alter_username_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='username',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='パスワード'),
        ),
        migrations.AlterField(
            model_name='username',
            name='user_name',
            field=models.CharField(max_length=50, verbose_name='ユーザ名'),
        ),
    ]
