# Generated by Django 5.2.4 on 2025-08-11 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_tags_remove_article_tag_article_tag'),
        ('app1', '0009_guidebook_article_score'),
    ]

    operations = [
    ]
