# Generated by Django 4.2.23 on 2025-08-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_article_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidebook',
            name='tag',
        ),
        migrations.AddField(
            model_name='guidebook',
            name='tag_id',
            field=models.IntegerField(default='1', verbose_name='タグID'),
        ),
        migrations.AlterField(
            model_name='guidebook',
            name='articles',
            field=models.IntegerField(null=True, verbose_name='参照した投稿の数'),
        ),
        migrations.AlterField(
            model_name='guidebook',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='作成時間'),
        ),
    ]
